[selfmon]

enabled = true #true with ""
freq = 30
prefix = "gvm"
extratags = [ "instance=lan" ]

[snmp]
#--------------------------
#  CONETION PARAMETERS
#--------------------------

# host : hostname or IP (no default)
# port : conection port (no default)
# timeout : Timeout is the timeout for the SNMP Query in seconds
# retries : Set the number of retries to attempt within timeout.
# repeat : (Not used yet)

#--------------------------------
#   SNMP VERSION/AUTH PARAMETERS
#-------------------------------- 

# snmpversion 	: posible values values [ "1", "2c" , "3"] ( no default set)
# community 	: (por snmpv2 only) commumity for authentication (no default set)
#
# -- for SNMP v3 only --
#
# v3seclevel	:  posible values [ "NoAuthNoPriv" , "AuthNoPriv" , "AuthPriv" ] ( no default set)
# v3authuser 	:  Authentication user  
# v3authpass	:  Autentication password
# v3authprot 	:  Autehtication Protocol =>  values  [ "MD5", "SHA" ] ( default none)
#
# -- only needed if AuthPriv mode enabled ---
#
# v3privpass 	: Privacy Password
# v3privprot 	: Privacy Protocol => values [ "DES", "AES"] ( default none)

# ---------------------------
# RUNTIME OPTIONS
# --------------------------
#
# freq 		: Frequency of polling in seconds ( default none)
# extratags 	: Array with extratags in format key = value will be sent to the influxdb database 
# portfile 	: file with port filter
# debug		:


[snmp.hostsnmpv2_1]
#conection parameters
host = "127.0.0.1"
port = 161
timeout = 20
retries = 5
#repeat = 0
#snmp version /auth params
snmpversion = "2c"  
community = "public"
# runtime parameters
freq = 30
extratags = [ "tagA=1","tagB=2" , "tagC=3" ]
#debug = true
# if port file is ommited than all columns will be retrieved
#portfile =  sample_ports.txt

[snmp.hostsnmpv2_2]
#conection parameters
host = "hostsnmpv2_2"
port = 161
timeout = 20
retries = 5
#repeat = 0
#snmp version /auth params
snmpversion = "2c"  
community = "public"
# runtime parameters
freq = 30
extratags = [ "tagA=1","tagB=2" , "tagC=3" ]
#debug = true
# if port file is ommited than all columns will be retrieved
#portfile =  sample_ports.txt



[snmp.hostsnmpv3a]
#conection parameters
host = "hostsnmpv3a"
port = 161
timeout = 20
retries = 5
repeat = 0
#snmp version /auth params
snmpversion = "3"
v3seclevel = "NoAuthNoPriv"
#only needed if Auth v3 enabled
v3authuser = "v3usernoauth"
# runtime parameters
freq = 30
extratags = [ "tagA=4","tagB=5" ,"tagC=6" ]
debug  = true
# if port file is ommited than all columns will be retrieved
#portfile =  sample_ports.txt

[snmp.hostsnmpv3b]
#conection parameters
host = "hostsnmpv3b"
port = 161
timeout = 20
retries = 5
repeat = 0
#snmp version /auth params
snmpversion = "3"
v3seclevel = "AuthNoPriv"
#only needed if Auth v3 enabled
v3authuser = "v3userauth"
v3authpass = "v3passauth"
v3authprot = "MD5"
# runtime parameters
freq = 30
#extratags = [ "tagA=4","tagB=5" ,"tagC=6" ]
#debug  = true
# if port file is ommited than all columns will be retrieved
#portfile =  sample_ports.txt

[snmp.hostsnmpv3c]
#conection parameters
host = "hostsnmpv3c"
port = 161
timeout = 20
retries = 5
repeat = 0
#snmp version /auth params
snmpversion = "3"
v3seclevel = "AuthPriv"
#only needed if Auth v3 enabled
v3authuser = "v3userpriv"
v3authpass = "v3passpriv"
v3authprot = "MD5"
#only needed if Privacy v3 enabled
v3privpass = "v3passenc"
v3privprot = "DES"
# runtime parameters
freq = 30
extratags = [ "tagA=4","tagB=5" ,"tagC=6" ]
#debug  = true
# if port file is ommited than all columns will be retrieved
#portfile =  sample_ports.txt

[mibs]
[mibs."*"]
name = "ifXEntry"
scalers = false
columns = [
	"ifHCInOctets",
	"ifHCInUcastPkts",
	"ifHCOutOctets",
	"ifHCOutUcastPkts"
	]

[mibs."switch"]
name = "ifXEntry"
columns = [
	"ifHCInOctets",
	"ifHCOutOctets"
	]

[influx]

[influx."*"]
host = "192.168.1.103"
port = 8086
db = "snmp"
user = "snmpuser"
password = "snmppass"

[http]
port   = 8090
