[selfmon]

enabled = true #true with ""
freq = 30
prefix = "gvm"
extratags = [ "instance=lan" ]

[snmp]

[snmp."hostname1"]
#conection parameters
host = "127.0.0.1"
port = 161
timeout = 20
retries = 5
repeat = 0
#snmp version /auth params
snmpversion = "2c"   # values [ "1", "2c" , "3"]
community = "public"
# runtime parameters
freq = 30
extratags = [ "tagA=1","tagB=2" , "tagC=3" ]
# if port file is ommited than all columns will be retrieved
#portfile =  sample_ports.txt

[snmp.hostname2]
#conection parameters
host = "192.168.1.99"
port = 161
timeout = 20
retries = 5
repeat = 0
#snmp version /auth params
snmpversion = "3"				# values [ "1", "2c" , "3"]
v3seclevel = "AuthPriv" # values [ "NoAuthNoPriv" , "AuthNoPriv" , "AuthPriv" ]
#only needed if Auth v3 enabled
v3authuser = "v3userpriv"
v3authpass = "v3passpriv"
v3authprot = "MD5"  # Autehtication Protocol =>  values  [ "MD5", "SHA" ]
#only needed if Privacy v3 enabled
v3privpass = "v3passenc"
v3privprot = "DES" # Privacy Protocol => values [ "DES", "AES"]

# runtime parameters
freq = 30
extratags = [ "tagA=4","tagB=5" ,"tagC=6" ]

#debug  = true
# if port file is ommited than all columns will be retrieved
#portfile =  sample_ports.txt

[mibs]
[mibs."*"]
name = "ifXEntry"
scalers = false
columns = [
	"ifHCInOctets",
	"ifHCInUcastPkts",
	"ifHCOutOctets",
	"ifHCOutUcastPkts"
	]

[mibs."switch"]
name = "ifXEntry"
columns = [
	"ifHCInOctets",
	"ifHCOutOctets"
	]

[influx]

[influx."*"]
host = "192.168.1.103"
port = 8086
db = "snmp"
user = "snmpuser"
password = "snmppass"

[http]
port   = 8090
