[selfmon]

enabled = true #true with ""
freq = 30
prefix = "gvm"
extratags = [ "instance=lan" ]

[snmp]

[snmp."hostname1"]
host = "127.0.0.1"
community = "public"
port = 161 
timeout = 20
retries = 5
repeat = 0
freq = 30
extratags = [ "tagA=1","tagB=2" , "tagC=3" ]
# if port file is ommited than all columns will be retrieved
#portfile =  sample_ports.txt

[snmp.hostname2]
host = "127.0.0.2"
community = "public"
port = 161
timeout = 20
retries = 5
repeat = 0
freq = 30
extratags = [ "tagA=4","tagB=5" ,"tagC=6" ]

#debug  = true
# if port file is ommited than all columns will be retrieved
#portfile =  sample_ports.txt

[mibs]
[mibs."*"]
name = "ifXEntry"
scalers = false
columns = [ 
	"ifHCInOctets",
	"ifHCInUcastPkts",
	"ifHCOutOctets",
	"ifHCOutUcastPkts"
	]

[mibs."switch"]
name = "ifXEntry"
columns = [
	"ifHCInOctets",
	"ifHCOutOctets"
	] 

[influx]

[influx."*"]
host = "192.168.1.103"
port = 8086
db = "snmp"
user = "snmpuser"
password = "snmppass"

[http]
port   = 8090


